default['rsyslog']['max_message_size'] = '32k'
default['keboola-transformation-db']['register'] = 'No'
default['keboola-transformation-db']['mysql']['default-password'] = ''
default['keboola-transformation-db']['provisioning-manage-api']['token'] = ''
default['keboola-transformation-db']['provisioning-manage-api']['url'] = ''
default['keboola-transformation-db']['mysql']['innodb-buffer-pool-size'] = '54G'
default['keboola-transformation-db']['type'] = 'transformations'
